name: NodeJS with Webpack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Git
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        
    - name: Build
      run: |
        git checkout -b gh-pages
        git worktree add -f dist gh-pages
        npm install
        npm run build
        git add -f dist
        git commit -m "added build files"
        git subtree push -f --prefix dist origin gh-pages

